name: Parallel jobs
on: 
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:  
            - name: Install the cowsay
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dog "Run for cover, I am a dog Rawr..." >> dog.txt

            - name: Sleep for 10 seconds
              run: sleep 10

    test:
        runs-on: Ubuntu-latest
        steps:
            - name: Sleep for 10 seconds
              run: sleep 10

            - name: Test file exists
              run: grep -i "Dragon" Dragon.txt
    deploy: 
        runs-on: ubuntu-latest
        steps:         
            - name: Read the file
              run: cat Dragon.txt

            - name: deploy
              run: echo "Deploying..."
