name: execute the shell script
on: push
jobs:
    execute:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: List the repo
              run: ls -ltra

            - name: Execute the script
              run: |
                chmod +x ascii_script.sh
                ./ascii_script.sh

